name: PHP_CodeSniffer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install PHP_CodeSniffer
        run: |
          composer global require "squizlabs/php_codesniffer=*"
          export PATH="$PATH:$HOME/.composer/vendor/bin"
      - name: Run PHP_CodeSniffer
        run: phpcs . --standard=PSR12
